# Duty Schedule Configuration
schedule:
  # Month and Year for the duty schedule
  year: 2025
  month: 9 # February
  # CSV source URL
  csv_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRp8jWocqu5XM_O7c8T_bvAZjQQpNHVu6r70sj-8r17WRgDdSnQG9rlCzD_4D603lkWthoX1PrFSosF/pub?gid=908128197&single=true&output=csv"
# Time settings
duty_times:
  # Weekday duty: 17:00 to next day 08:00
  weekday:
    start_time: "17:00"
    end_time: "08:00" # next day
  # Weekend duty: 08:00 to next day 08:00
  weekend:
    start_time: "08:00"
    end_time: "08:00" # next day
# Calendar content customization
calendar:
  # Main calendar title template (use {person} for person name, {location} for location)
  title_template: "{location}值班"
  # Event title template
  event_title_template: "{duty_type} - {location}"
  # Event description template
  event_description_template: |
    {duty_type} - {location}
    日期: {date}
    時間: {start_time} - {end_time}

    請準時到崗，注意交接事項。
  # Alarm reminder message
  alarm_message_template: "提醒：您的{location}{duty_type}將在30分鐘後開始！"
  # Physical address for calendar events
  physical_address: "11209台北市北投區立德路125號"
# CSV data organization
csv_format:
  # How is your data organized?
  # "columns": Days are in columns (A1=day1, B1=day2, C1=day3...)
  # "rows": Days are in rows (A1=day1, A2=day2, A3=day3...)
  orientation: "rows"
# Location mapping based on CSV structure
locations:
  # Column-based location mapping (0-based column index)
  by_column:
    0: "北邊及六樓" # Column A (column 0) = 北邊病房
    1: "綜合五南" # Column B (column 1) = 南邊病房
    # Add more columns as needed
    # 2: "東邊病房"  # Column C
    # 3: "西邊病房"  # Column D
  # Default location if column not found in mapping
  default: "一般病房"
# Duty type translations
duty_types:
  weekday: "平日值班"
  weekend: "假日值班"
# Output settings
output:
  directory: "output"
  filename_pattern: "duty_{char}_{location}.ics"
